MyBlog2/MyBlog2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about, name='about'),
    url(r'^$', article_views.articles, name="home"),
]

urlpatterns+= staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyBlog2/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'account_app'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

MyBlog2/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'article_app'

urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'^create/$', views.create_article, name='article_create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='article_detail'),
]

MyBlog2/accounts/models.py
from django.db import models

# Create your models here.

MyBlog2/articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100,)
    slug = models.SlugField()
    body = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    # add thumbnail and author later

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:100] + '....'

MyBlog2/articles/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title','body','slug','thumb',]

MyBlog2/MyBlog2/views.py
from django.http import HttpResponse
from django.shortcuts import render


def about(request):
    return render(request, 'about.html', context={})

def home(request):
    return render(request, 'home.html', context={})

MyBlog2/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

# Create your views here.
def signup_view(request):

    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login (request, user)
            return redirect('article_app:articles')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', context={'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('article_app:articles')
                #log in the user


    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', context={'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return HttpResponseRedirect(reverse_lazy('article_app:articles'))

MyBlog2/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
# Create your views here.
def articles(request):
    articles = Article.objects.all().order_by('publish_date')
    return render(request, 'articles/articles_list.html', context={'articles':articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_details.html', context={'article':article})

@login_required(login_url="/accounts/login/")
def create_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article_app:articles')
            #save form in database
    else:
        form = ArticleForm()
    return render(request, 'articles/article_create.html', context={'form':form})

MyBlog2/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login Page</h1>
<form class="site-form" method="post">
      {{form.as_p}}
      {% csrf_token %}
      {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
      {% endif %}
      <input type="Submit" name="" value="Login">
</form>

{% endblock %}

MyBlog2/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<form class="site-form" method="post">
      {{form}}
      <input type="Submit" name="" value="signup">
      {% csrf_token %}
</form>

{% endblock %}

MyBlog2/articles/templates/articles/article_create.html
{% extends 'base.html' %}
{% block content %}

<div class="create-article">
  <form class="site-form" action="{% url 'article_app:article_create' %}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="Submit" name="" value="Create">
  </form>
</div>
<script src="/static/slugify.js">
</script>
{% endblock %}

MyBlog2/articles/templates/articles/article_details.html
{% extends 'base.html' %}

{% block content %}

{% if article %}
<div class="article-detail">
<div class="article">
<img src="{{article.thumb.url}}" alt="" width="100%" >
<h1 style="align:center">{{article.title}}</h1>
<p>{{article.body}}</p>
<p>Published on: {{article.publish_date}}</p>
{% else %}
<h1>Article is not reachable at this moment</h1>
 </div>
</div>
{% endif %}
{% endblock %}

MyBlog2/articles/templates/articles/articles_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
      {% for article in articles %}
      <div class="article">
        <h3><a href="{% url 'article_app:article_detail' slug=article.slug %}">{{article.title}}</a></h3>
        <p>{{article.snippet}}</p>
        <p>{{article.publish_date}}</p>
      </div>
    </div>
    {% endfor %}
    <h3>More about the articles <a href="about/">here</a></h3>
    <a href="{% url 'article_app:article_create' %}">Create a new article</a>
{% endblock %}

MyBlog2/templates/about.html
<!DOCTYPE html>
<html lang="" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>This is the about page babbbbyyyyyyyyy!!</h1>
    <a href="/">Go to home page baby</a>
  </body>
</html>

MyBlog2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{%static 'logo.png' %}" alt=""></a></h1>
          {% if user.is_authenticated %}
          <ul>
            <li><a href="{% url 'article_app:article_create' %}"><button type="button" name="button">Create A new article</button></a></li>
              <li>
          <form class="logout-link" action="{% url 'account_app:logout' %}" method="post">
              {% csrf_token %}
              <button type="Submit" >Logout</button>
          </form>
        </li>
      </ul>
      {% else %}
      <ul>
        <li><a href="{% url 'account_app:signup' %}"><button type="button" name="button">Signup here</button></a></li>
        <li>  <a href="{% url 'account_app:login' %}"><button type="button" name="button">Login here</button></a></li>
        </ul>
        {% endif %}
        {% block content %}

        {% endblock %}
    </div>
  </body>
  </html>

MyBlog2/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the Homepage Baby</h1>
    <a href="about">Go to about page baby</a>
    <h3>Check out the articles <a href="articles">here</a></h3>
  </body>
</html>